# Generated by Django 5.1.7 on 2025-04-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_app', '0003_alter_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name']},
        ),
    ]
