# Generated by Django 5.1.7 on 2025-04-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function_app', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
