# Generated by Django 5.1.7 on 2025-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_app', '0005_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
