# Generated by Django 5.1.7 on 2025-03-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_borrowed_books_count_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='borrowed_books_count',
        ),
    ]
